### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by scott-martinez** [JosephSWilliams/urcd#1]
It is not clear what the terms for this software are. Can this please be clarified in the git repository? I can only find a "Copyleft (c) 2015 Joseph S. Williams" and a license file which is a symlink to /dev/null. Do I take that to mean that this has no license? Just because you're opting out of giving it a license doesn't mean you're opting out of copyright. In the absence of a license, default copyright rules apply (aka "All Rights Reserved") which means: No modifications by third parties, no redistribution by third parties, etc. (Because, thanks to things like the Berne Convention, which most countries of the world have signed on to, things get copyrighted as All Rights Reserved by default merely regardless of the author's intent merely by existing... unless you take an explicit and overt action to do something else. Sad, but it's the world we live in and surely you want people to have the legal rights to modify and share the software right? May I suggest adopting the GNU Affero GPL version 3 with the "or any later version" clause? That would give you a strong copyleft (since you did say "copyleft" in the copyright file) and ensure that people `will be able to do exactly that.

**Comment by scott-martinez** [comment]
er, part of that didn't come out quite right. Part of that is supposed to be worded as "...things get copyrighted as All Rights Reserved by default merely by existing regardless of the author's intent..."

**Comment by pizzamaker** [comment]
+1

Please add a free license :)

**Comment by JosephSWilliams** [comment]
People have been asking me for a "free" license. Thus, I have published URCd under the Holistics License. This is a copyleft license similar to the GPL. There are a few differences to my license:

The Holistics License has stronger copyleft provisions.
It can adapt and evolve faster than the GPL family of licenses.
It creates a power group.
It is engineered for business.

http://Holistics.biz/legal

**Comment by scott-martinez** [comment]
I am not sure that this license qualifies as free. It seems to have some problematic aspects. Rather than making your own and raising problematic things, can you select from various well-established ones? There is a good list at http://www.gnu.org/licenses/license-list.html#SoftwareLicenses

**Comment by JosephSWilliams** [comment]
Hey Scott, That's a prototype I am working on for another project. I reissued it under GPLv3. Thanks :-)

**Comment by JosephSWilliams** [comment]
I think copyright is a ridiculous concept, but I can understand your concern. My goal with the other license is to make software marketable and still be free. Which that gave me a good idea. Thanks for asking. For now I will leave it as GPLv3, but you don't ever have to worry about the software coming with restrictive provisions or digital "handcuffs".

**Comment by scott-martinez** [comment]
Thank you very much for placing this under GPLv3 with the any later version clause.
